version: "3"
services:
  mongo-router:
    image: ${MONGO_IMG_TAG}
    restart: always
    hostname: mongo-router
    container_name: mongo-router
    ports:
      - 27017:27017
    external_links:
      - mongo-rs1-setup
      - mongo-rs2-setup
      - mongo-conf-setup
      - mongo-conf-s1
      - mongo-conf-s2
      - mongo-conf-s3
      - mongo-r1-s1
      - mongo-r1-s2
      - mongo-r1-s3
      - mongo-r2-s1
      - mongo-r2-s2
      - mongo-r2-s3
    command: ${ROUTER_CMD}

  mongo-shard-setup:
    image: ${MONGO_IMG_TAG}
    hostname: mongo-shard-setup
    container_name: mongo-shard-setup
    depends_on:
      - mongo-router
    volumes:
      - ./scripts/entrypoint:/scripts
    environment:
      - MONGOS=mongo-router
      - MONGO11=mongo-r1-s1
      - MONGO12=mongo-r1-s2
      - MONGO13=mongo-r1-s3
      - MONGO21=mongo-r2-s1
      - MONGO22=mongo-r2-s2
      - MONGO23=mongo-r2-s3
      - RS1=rs1
      - RS2=rs2
      - PORT=27017
      - PORT1=27017
      - PORT2=27017
      - PORT3=27017
    entrypoint: ["/scripts/init-shard.sh"]
    restart: on-failure:20
