version: "3"
services:
  mongo-r1-s2:
    image: ${MONGO_IMG_TAG}
    restart: always
    hostname: mongo-r1-s2
    container_name: mongo-r1-s2
    command: mongod --replSet rs1 ${RC_CMD_OPT}
    volumes:
      - ./data/mongo-r1-s2:/data/db

  mongo-r1-s3:
    image: ${MONGO_IMG_TAG}
    restart: always
    hostname: mongo-r1-s3
    container_name: mongo-r1-s3
    command: mongod --replSet rs1 ${RC_CMD_OPT}
    volumes:
      - ./data/mongo-r1-s3:/data/db

  mongo-r1-s1:
    image: ${MONGO_IMG_TAG}
    restart: always
    hostname: mongo-r1-s1
    container_name: mongo-r1-s1
    command: mongod --replSet rs1 ${RC_CMD_OPT}
    volumes:
      - ./data/mongo-r1-s1:/data/db
    links:
      - mongo-r1-s2
      - mongo-r1-s3

  mongo-rs1-setup:
    image: ${MONGO_IMG_TAG}
    container_name: mongo-rs1-setup
    depends_on:
      - mongo-r1-s1
      - mongo-r1-s2
      - mongo-r1-s3
    volumes:
      - ./scripts/entrypoint:/scripts
    environment:
      - MONGO1=mongo-r1-s1
      - MONGO2=mongo-r1-s2
      - MONGO3=mongo-r1-s3
      - RS=rs1
    entrypoint: ["/scripts/setup.sh"]
    restart: on-failure:20
