---
# MySQL Version: 5.7
# 
# FileVersion: 20191114

# Dockerfile
# https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile
# https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:

  mysql-g2-s1:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g2-s1
    container_name: mysql-g2-s1
    volumes:
      - ./conf/gtid/yh-master.cnf:/etc/mysql/conf.d/yh-master.cnf
      - ./conf/nodes/g1-s1.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ./data/mysql-g2-s1:/var/lib/mysql
      - ../../../log/mysql:/var/log/mysql
    ports:
      - 3326:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MASTER_PASSWD}"
    networks:
      - mysql-cluster-g2

  mysql-g2-s2:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g2-s2
    container_name: mysql-g2-s2
    depends_on:
      - mysql-g2-s1
    volumes:
      - ./conf/gtid/yh-slave.cnf:/etc/mysql/conf.d/yh-slave.cnf
      - ./conf/nodes/g1-s2.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ./data/mysql-g2-s2:/var/lib/mysql
      - ../../../log/mysql:/var/log/mysql
    ports:
      - 3327:3306
    environment:                           
      - "MYSQL_ROOT_PASSWORD=${SLAVE_PASSWD}"
    networks:
      - mysql-cluster-g2

  mysql-g2-s3:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g2-s3
    container_name: mysql-g2-s3
    depends_on:
      - mysql-g2-s1
    volumes:
      - ./conf/gtid/yh-slave.cnf:/etc/mysql/conf.d/yh-slave.cnf
      - ./conf/nodes/g1-s3.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ./data/mysql-g2-s3:/var/lib/mysql
      - ../../../log/mysql:/var/log/mysql
    ports:
      - 3328:3306
    environment:                           
      - "MYSQL_ROOT_PASSWORD=${SLAVE_PASSWD}"
    networks:
      - mysql-cluster-g2


networks:
  mysql-cluster-g2:
    driver: bridge
