---
# Nginx Version: 1.16.0-alpine-perl, 1.16.0-alpine
# https://hub.daocloud.io/repos/2b7310fb-1a50-48f2-9586-44622a2d1771


version: '3'
services:
  nginx:
    image: nginx:1.16.0-alpine-perl
    container_name: dev-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d # 配置文件子目录
      - ./nginx/html:/usr/share/nginx/html # 静态资源根目录
      - ../../log/nginx:/var/log/nginx # 日志文件
    ports:
      - 50080:80
