---
# CentOS 测试 集群
# Version: 20191103


version: '3'

services:

  test-m1:
    image: centos:7
    hostname: test-m1
    container_name: test-m1
    command: /usr/sbin/init
    privileged: true
    volumes:
      - ./os-c7-cluster/test-m1:/data # 数据目录
      - ../../:/project # 本项目目录
    ports:
      - "42201:22"
    networks:
      - test-os-c7-cluster

  test-n1:
    image: centos:7
    hostname: test-n1
    container_name: test-n1
    command: /usr/sbin/init
    privileged: true
    volumes:
      - ./os-c7-cluster/test-n1:/data # 数据目录
      - ../../:/project # 本项目目录
    ports:
      - "42211:22"
    networks:
      - test-os-c7-cluster

  test-n2:
    image: centos:7
    hostname: test-n2
    container_name: test-n2
    command: /usr/sbin/init
    privileged: true
    volumes:
      - ./os-c7-cluster/test-n2:/data # 数据目录
      - ../../:/project # 本项目目录
    ports:
      - "42212:22"
    networks:
      - test-os-c7-cluster

networks:
  test-os-c7-cluster:
    driver: bridge
