---
# Name: Elastic Stack 
# Version: https://www.docker.elastic.co/
# FileVersion: 20191106
# Ref: 
#   - https://www.elastic.co/guide/en/elasticsearch/reference/7.4/docker.html


# Dockerfile
# 


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '2.2'
services:
  es01:
    image: elasticsearch:7.3.2
    hostname: es01
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: elasticsearch:7.3.2
    hostname: es02
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: elasticsearch:7.3.2
    hostname: es03
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:7.3.2
    hostname: kibana
    container_name: kibana
    # environment:
    #   - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./logs:/var/log
    links:
      - es01
      - es02
      - es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  nginx:
    image: nginx:latest
    ports:
      - 18081:80
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 655350
    networks:
      - elastic
      - ingress

# volumes:
#   data01:
#     driver: local
#   data02:
#     driver: local
#   data03:
#     driver: local

networks:
  elastic:
  ingress:


# ####################################
# FAQ
# ####################################
# ERROR: [1] bootstrap checks failed
# [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
# 
# Seeto: https://www.elastic.co/guide/en/elasticsearch/reference/7.3/docker.html#docker-prod-cluster-composefile
# 
# 解决方案: 
#   - (一定要)在宿主机上，执行: sysctl -w vm.max_map_count=262144
# 
